import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { ArrowLeft, ArrowRight, Gift, Heart, Music2, Pause, Play, RotateCcw, Volume2, VolumeX } from "lucide-react";
import floralWreath from "../assets/romantic-floral-wreath.png";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "A Special Surprise for My Januu" },
    { name: "description", content: "A magical birthday love letter from Uzan Khan to My Januu." },
    { property: "og:title", content: "A Special Surprise for My Januu" },
    { property: "og:description", content: "A magical birthday love letter from Uzan Khan to My Januu." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: BirthdaySurprise,
});

const chapterNames = ["Welcome", "Secret", "Wish", "Cake", "Memories", "Fun", "Letter", "Forever"];
const memories = [
  ["🌅", "Remember this day?"], ["💬", "Our first conversation…"],
  ["😂", "This was so funny!"], ["💞", "Forever my favourite memory"],
];
const reasons = ["Your smile makes every day brighter.","You understand my silences.","You make ordinary moments magical.","Your laugh is my favourite sound.","You are endlessly kind.","You believe in me.","You make me feel at home.","Every memory is better with you.","You are beautifully, wonderfully you.","Simply: you are my Januu. 💗"];
const jarMemories = ["The first time you made me forget what I was saying.","That laugh I could listen to forever.","The little conversations that became my favourite memories.","Every time a simple hello made my whole day."];

function MagicButton({ children, onClick, type="button", disabled=false, className="" }: { children:ReactNode;onClick?:()=>void;type?:"button"|"submit";disabled?:boolean;className?:string }) {
  return <button type={type} disabled={disabled} onClick={onClick} className={`magic-button inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-primary px-6 py-3 font-semibold text-primary-foreground transition disabled:cursor-not-allowed disabled:opacity-40 ${className}`}>{children}</button>;
}

function BirthdaySurprise() {
  const [chapter,setChapter]=useState(0); const [unlocked,setUnlocked]=useState(false);
  const [playing,setPlaying]=useState(false); const [volume,setVolume]=useState(.18); const audio=useRef<AudioContext|null>(null); const timer=useRef<number|null>(null);
  const [confetti,setConfetti]=useState<number[]>([]); const [countdown,setCountdown]=useState("");
  useEffect(()=>{ const tick=()=>{const now=new Date();let target=new Date(now.getFullYear(),9,1);if(now>target)target=new Date(now.getFullYear()+1,9,1);const d=target.getTime()-now.getTime();setCountdown(`${Math.floor(d/86400000)}d  ${Math.floor(d/3600000)%24}h  ${Math.floor(d/60000)%60}m  ${Math.floor(d/1000)%60}s`)};tick();const id=window.setInterval(tick,1000);return()=>clearInterval(id)},[]);
  useEffect(()=>{const move=(e:PointerEvent)=>{if(Math.random()>.62){const s=document.createElement("span");s.className="cursor-heart";s.textContent=Math.random()>.5?"💗":"✨";s.style.left=`${e.clientX}px`;s.style.top=`${e.clientY}px`;document.body.appendChild(s);setTimeout(()=>s.remove(),800)}};window.addEventListener("pointermove",move);return()=>window.removeEventListener("pointermove",move)},[]);
  useEffect(()=>()=>{if(timer.current)window.clearInterval(timer.current);audio.current?.close()},[]);
  const sound=(notes=[523.25,659.25,783.99])=>{try{const ctx=audio.current??new AudioContext();audio.current=ctx;notes.forEach((n,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type="sine";o.frequency.value=n;g.gain.setValueAtTime(volume*.18,ctx.currentTime+i*.1);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+i*.1+.35);o.connect(g).connect(ctx.destination);o.start(ctx.currentTime+i*.1);o.stop(ctx.currentTime+i*.1+.36)})}catch{return}};
  const toggleMusic=()=>{if(!playing){sound([261.63,329.63,392,523.25]);timer.current=window.setInterval(()=>sound([261.63,329.63,392,523.25]),4300);setPlaying(true)}else{if(timer.current)window.clearInterval(timer.current);setPlaying(false)}};
  const celebrate=()=>{setConfetti(Array.from({length:55},(_,i)=>Date.now()+i));sound([523,659,784,1047]);setTimeout(()=>setConfetti([]),3000)};
  const go=(n:number)=>{setChapter(Math.max(0,Math.min(7,n)));sound([440,587]);};
  return <main onClick={(e)=>{const el=e.target as HTMLElement;const r=document.createElement("i");r.className="cursor-heart";r.textContent="✨";r.style.left=`${e.clientX}px`;r.style.top=`${e.clientY}px`;document.body.appendChild(r);setTimeout(()=>r.remove(),800)}} className="dream-bg relative h-[100dvh] overflow-hidden text-foreground selection:bg-primary/20">
    <MagicSky />
    {confetti.map((id,i)=><i key={id} className="confetti-piece h-3 w-2 rounded-sm bg-gold" style={{left:`${(i*37)%100}%`,`--dx`:`${(i%2?1:-1)*(20+i%50)}px`,animationDelay:`${(i%9)*.04}s`} as React.CSSProperties}/>)}
    {chapter>0&&<header className="fixed inset-x-0 top-0 z-50 grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 p-3 sm:p-5">
      <button aria-label="Previous chapter" onClick={()=>go(chapter-1)} className="grid size-10 place-items-center rounded-full border border-border bg-paper/80 text-primary backdrop-blur"><ArrowLeft size={18}/></button>
      <div className="mx-auto flex max-w-xl items-center gap-1.5" aria-label={`Chapter ${chapter+1} of 8`}>
        {chapterNames.map((n,i)=><button key={n} aria-label={n} onClick={()=>unlocked&&go(i)} className={`grid size-6 place-items-center text-xs transition sm:size-8 ${i<=chapter?"text-primary":"text-muted-foreground/40"}`}>{i<=chapter?"♥":"♡"}</button>)}
      </div><span className="hidden text-xs font-medium text-muted-foreground sm:block">{chapterNames[chapter]}</span>
    </header>}
    <section className="scrollbar-soft relative z-10 h-full overflow-y-auto px-4 pb-24 pt-16 sm:px-8">
      {chapter===0&&<Welcome countdown={countdown} onStart={()=>{toggleMusic();go(1)}}/>}
      {chapter===1&&<Lock onUnlock={()=>{setUnlocked(true);celebrate();setTimeout(()=>go(2),1900)}}/>}
      {chapter===2&&<Wish onNext={()=>go(3)}/>} {chapter===3&&<Cake celebrate={celebrate} onNext={()=>go(4)}/>} {chapter===4&&<MemoryLane onNext={()=>go(5)}/>} {chapter===5&&<FunZone onNext={()=>go(6)} celebrate={celebrate}/>} {chapter===6&&<Letter onNext={()=>go(7)}/>} {chapter===7&&<Finale celebrate={celebrate} onReplay={()=>{setUnlocked(false);setChapter(0)}}/>}
    </section>
    <div className="fixed bottom-4 right-4 z-50 flex items-center gap-2 rounded-full border border-border bg-paper/85 p-2 shadow-lg backdrop-blur">
      <button aria-label={playing?"Pause music":"Play music"} onClick={toggleMusic} className="grid size-9 place-items-center rounded-full bg-primary text-primary-foreground">{playing?<Pause size={16}/>:<Play size={16}/>}</button>
      <button aria-label={volume?"Mute":"Unmute"} onClick={()=>setVolume(volume?0:.18)} className="grid size-8 place-items-center text-primary">{volume?<Volume2 size={16}/>:<VolumeX size={16}/>}</button>
      <input aria-label="Volume" className="hidden w-20 accent-primary sm:block" type="range" min="0" max="0.5" step="0.02" value={volume} onChange={e=>setVolume(Number(e.target.value))}/>
    </div>
    <footer className="fixed bottom-3 left-4 z-40 text-[10px] text-muted-foreground sm:text-xs">Made with 💗 by Uzan Khan for My Januu</footer>
  </main>;
}

function MagicSky(){return <div aria-hidden className="pointer-events-none fixed inset-0 z-0 overflow-hidden">{Array.from({length:12},(_,i)=><span key={`p${i}`} className="petal text-lg" style={{left:`${i*9}%`,animationDuration:`${10+i%5}s`,animationDelay:`-${i*.8}s`}}>{i%3===0?"🌸":"🌷"}</span>)}{Array.from({length:10},(_,i)=><span key={`h${i}`} className="heart-float text-sm" style={{left:`${(i*13)%100}%`,animationDuration:`${9+i%6}s`,animationDelay:`-${i*1.2}s`}}>♡</span>)}<span className="shooting-star absolute top-6 text-gold">✦ ─────</span></div>}
function Frame({children,className=""}:{children:ReactNode;className?:string}){return <div className={`mx-auto w-full max-w-3xl rounded-lg border border-paper/70 bg-paper/70 p-5 shadow-[0_20px_70px_color-mix(in_oklab,var(--primary)_18%,transparent)] backdrop-blur-md sm:p-10 ${className}`}>{children}</div>}

function Welcome({countdown,onStart}:{countdown:string;onStart:()=>void}){const [gift,setGift]=useState(false);return <div className="chapter mx-auto flex min-h-[calc(100dvh-5rem)] max-w-5xl flex-col items-center justify-center text-center"><div className="relative mb-2 size-32 sm:size-44"><img src={floralWreath} alt="Pink roses and white lilies" width={1024} height={1024} className="size-full rounded-full object-cover shadow-xl"/><Gift className="floaty absolute inset-0 m-auto text-primary" size={44}/></div><p className="mb-2 text-xs font-semibold uppercase tracking-[.22em] text-muted-foreground">October 1 • a little world made for you</p><h1 className="script max-w-4xl text-5xl font-bold leading-tight text-primary drop-shadow-sm sm:text-7xl">A Special Surprise for My Januu 💗</h1><p className="quote mt-4 text-lg italic text-foreground/75">Something magical, made just for you…</p><div className="my-7 rounded-lg border border-border bg-paper/55 px-5 py-3"><span className="block text-[10px] uppercase tracking-[.2em] text-muted-foreground">Counting down to your day</span><strong className="mt-1 block tabular-nums text-primary">{countdown}</strong></div><div className="flex flex-wrap justify-center gap-3"><MagicButton onClick={onStart}>Click to Start <span>✨</span></MagicButton><button onClick={()=>setGift(!gift)} aria-label="Open virtual gift" className="grid size-12 place-items-center rounded-full border border-primary/30 bg-paper text-primary transition hover:-translate-y-1"><Gift size={20}/></button></div>{gift&&<p className="quote mt-5 animate-fade-in text-lg italic text-primary">A lifetime supply of my love—no returns allowed. 🎁</p>}</div>}

function Lock({onUnlock}:{onUnlock:()=>void}){const [value,setValue]=useState("");const [error,setError]=useState(false);const [success,setSuccess]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();if(value==="for-you-i-will"){setSuccess(true);setError(false);onUnlock()}else{setError(true);setValue("");setTimeout(()=>setError(false),1200)}};return <div className="chapter flex min-h-[calc(100dvh-6rem)] items-center"><Frame className={`text-center ${error?"shake":""}`}><div className="floaty mx-auto mb-5 grid size-24 place-items-center rounded-full bg-rose-soft text-5xl shadow-xl">{success?"💖":"🔐"}</div><h2 className="script text-5xl font-bold text-primary">{success?"Welcome, My Januu! 🎉":"Only for My Januu"}</h2><p className="mt-3 text-sm text-muted-foreground">Enter the secret code to unlock your surprise…</p><form onSubmit={submit} className="mx-auto mt-8 max-w-sm"><label className="sr-only" htmlFor="secret">Secret code</label><input id="secret" autoFocus type="password" value={value} onChange={e=>{setValue(e.target.value);setError(false)}} className="w-full rounded-full border border-border bg-background/70 px-5 py-3 text-center outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10" placeholder="Our secret code"/><MagicButton type="submit" className="mt-4 w-full">Unlock 💗</MagicButton>{error&&<p role="alert" className="mt-4 text-sm font-medium text-primary">Oops! That's not you 😜 Try again, My Januu!</p>}</form></Frame></div>}

function Wish({onNext}:{onNext:()=>void}){const text="You are my best friend, my crush, my everything. Today is your day, and I just want to see you smile. Without you, everything feels incomplete. You are the reason my world feels brighter. — Yours forever, Uzan Khan 💗";const [shown,setShown]=useState("");useEffect(()=>{let i=0;const id=setInterval(()=>{i++;setShown(text.slice(0,i));if(i>=text.length)clearInterval(id)},24);return()=>clearInterval(id)},[]);return <div className="chapter flex min-h-[calc(100dvh-6rem)] items-center"><Frame className="relative overflow-hidden text-center"><span className="text-5xl">🎂</span><h2 className="script mt-4 text-5xl font-bold text-primary sm:text-6xl">Happy Birthday, My Januu!</h2><p className="quote mx-auto mt-7 min-h-40 max-w-2xl text-lg leading-8 italic sm:min-h-32 sm:text-xl">{shown}<span className="animate-pulse text-primary">|</span></p><div className="my-5 text-3xl tracking-[.35em]">🎈 💖 ✨ 🎉 🌸</div><MagicButton onClick={onNext}>Make a wish <ArrowRight size={18}/></MagicButton></Frame></div>}

function Cake({celebrate,onNext}:{celebrate:()=>void;onNext:()=>void}){const [candles,setCandles]=useState([true,true,true]);const [cut,setCut]=useState(false);const blow=(i:number)=>{const next=candles.map((v,j)=>j===i?false:v);setCandles(next);if(next.every(v=>!v))celebrate()};const ready=candles.every(v=>!v);return <div className="chapter flex min-h-[calc(100dvh-6rem)] items-center"><div className="mx-auto w-full max-w-4xl text-center"><p className="text-xs font-semibold uppercase tracking-[.2em] text-muted-foreground">The sweetest chapter</p><h2 className="script text-5xl font-bold text-primary">Make a wish, My Januu</h2><p className="mt-2 text-sm text-muted-foreground">{ready?cut?"The first slice is yours! 🍰":"Now cut the cake! 🔪":"Tap each candle to blow it out 🕯️"}</p><div className="relative mx-auto mt-12 h-72 w-72 sm:h-80 sm:w-96"><div className="absolute left-1/2 top-0 flex -translate-x-1/2 gap-10">{candles.map((lit,i)=><button key={i} aria-label={`Blow out candle ${i+1}`} disabled={!lit} onClick={()=>blow(i)} className="relative h-24 w-6"><i className={`flame absolute left-1/2 top-0 h-7 w-4 -translate-x-1/2 rounded-[50%_50%_45%_45%] bg-gold transition ${lit?"opacity-100":"opacity-0"}`}/><i className="absolute bottom-0 left-1/2 h-16 w-3 -translate-x-1/2 rounded bg-primary/45"/></button>)}</div><button aria-label="Cut the birthday cake" disabled={!ready||cut} onClick={()=>{setCut(true);celebrate()}} className="absolute inset-x-0 bottom-0 mx-auto h-48 w-72 transition enabled:hover:scale-105"><span className="absolute bottom-1 left-1/2 h-24 w-64 -translate-x-1/2 rounded-lg border-4 border-paper bg-rose-soft shadow-xl"/><span className={`absolute bottom-20 left-1/2 h-20 w-48 -translate-x-1/2 rounded-lg border-4 border-paper bg-rose-soft transition duration-700 ${cut?"translate-x-4 rotate-3":""}`}/><span className="script absolute bottom-11 left-1/2 z-10 w-56 -translate-x-1/2 text-xl font-bold text-primary">Happy Birthday<br/>My Januu</span></button></div>{ready&&!cut&&<MagicButton onClick={()=>{setCut(true);celebrate()}}>Cut the cake 🔪</MagicButton>}{cut&&<div className="animate-fade-in"><p className="quote mb-4 text-xl italic text-primary">Wish granted! The first slice is yours, My Januu! 🍰</p><MagicButton onClick={onNext}>Memory lane <ArrowRight size={18}/></MagicButton></div>}</div></div>}

function MemoryLane({onNext}:{onNext:()=>void}){const [reason,setReason]=useState(-1);const [memory,setMemory]=useState("");return <div className="chapter mx-auto max-w-6xl py-8 text-center"><h2 className="script text-5xl font-bold text-primary">Our Beautiful Memories 💕</h2><p className="mt-2 text-sm text-muted-foreground">Every little moment with you belongs here.</p><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{memories.map(([icon,caption],i)=><article key={caption} className={`rounded-sm bg-paper p-3 pb-6 shadow-xl transition hover:-translate-y-2 hover:rotate-0 ${i%2?"rotate-2":"-rotate-2"}`}><div className="grid aspect-[4/5] place-items-center bg-gradient-to-br from-rose-soft to-lavender text-7xl">{icon}</div><p className="script mt-4 text-xl text-primary">{caption}</p></article>)}</div><p className="quote mt-10 text-xl italic">And many more memories to make… 💕</p><div className="mx-auto mt-8 grid max-w-3xl gap-4 sm:grid-cols-2"><button onClick={()=>setReason((reason+1)%reasons.length)} className="rounded-lg border border-border bg-paper/70 p-5 text-left transition hover:-translate-y-1"><span className="text-xs uppercase tracking-widest text-muted-foreground">Reason {reason+2} of 10</span><strong className="mt-2 block text-primary">{reason<0?"Tap to reveal why I love you":reasons[reason]}</strong></button><button onClick={()=>setMemory(jarMemories[Math.floor(Math.random()*jarMemories.length)])} className="rounded-lg border border-border bg-paper/70 p-5 text-left transition hover:-translate-y-1"><span className="text-xs uppercase tracking-widest text-muted-foreground">Memory jar 🫙</span><strong className="mt-2 block text-primary">{memory||"Pull out a tiny memory"}</strong></button></div><MagicButton onClick={onNext} className="mt-8">Let’s play <ArrowRight size={18}/></MagicButton></div>}

function FunZone({onNext,celebrate}:{onNext:()=>void;celebrate:()=>void}){const [tab,setTab]=useState(0);const labels=["Quiz","Scratch","Love Meter","Balloons","Emoji Guess"];return <div className="chapter mx-auto max-w-5xl py-7 text-center"><h2 className="script text-5xl font-bold text-primary">Fun Zone for My Januu 🎮</h2><div className="scrollbar-soft mt-6 flex gap-2 overflow-x-auto pb-2">{labels.map((x,i)=><button key={x} onClick={()=>setTab(i)} className={`shrink-0 rounded-full border px-4 py-2 text-sm transition ${tab===i?"border-primary bg-primary text-primary-foreground":"border-border bg-paper/60"}`}>{x}</button>)}</div><Frame className="mt-4 min-h-96">{tab===0&&<Quiz celebrate={celebrate}/>} {tab===1&&<Scratch/>} {tab===2&&<LoveMeter celebrate={celebrate}/>} {tab===3&&<Balloons celebrate={celebrate}/>} {tab===4&&<EmojiGuess celebrate={celebrate}/>}</Frame><MagicButton onClick={onNext} className="mt-6">Read your letter <ArrowRight size={18}/></MagicButton></div>}
function Quiz({celebrate}:{celebrate:()=>void}){const qs=["Which colour feels most like our story?","Which flower belongs in your birthday garden?","What is my favourite view?","What makes everything better?","How long will I choose you?"];const opts=[["Soft pink","Grey skies","Neon green"],["Lilies & roses","Cactus","None"],["The moon","You smiling","A screen"],["Your laugh","Mondays","Traffic"],["One day","A while","Forever"]];const ans=[0,0,1,0,2];const [q,setQ]=useState(0);const [score,setScore]=useState(0);const pick=(i:number)=>{if(i===ans[q])setScore(score+1);if(q===4)celebrate();setQ(Math.min(5,q+1))};if(q===5)return <div><div className="text-6xl">⭐</div><h3 className="script text-4xl text-primary">You know our love!</h3><p className="mt-3">Score: {score}/5 — but you’ll always be my perfect match.</p><button className="mt-5 text-sm text-primary underline" onClick={()=>{setQ(0);setScore(0)}}>Play again</button></div>;return <div><div className="mb-6 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary transition-all" style={{width:`${q*20}%`}}/></div><h3 className="quote text-xl">{qs[q]}</h3><div className="mx-auto mt-6 grid max-w-sm gap-3">{opts[q].map((o,i)=><button key={o} onClick={()=>pick(i)} className="rounded-full border border-border bg-background/60 px-4 py-3 transition hover:border-primary hover:text-primary">{o}</button>)}</div></div>}
function Scratch(){const msgs=["Your smile is the best in the world","You are my favourite person","Everything is boring without you"];const [open,setOpen]=useState<boolean[]>([false,false,false]);return <div><h3 className="script text-4xl text-primary">Scratch Card Surprise 🎁</h3><p className="mt-1 text-sm text-muted-foreground">Rub or tap each golden card.</p><div className="mt-8 grid gap-4 sm:grid-cols-3">{msgs.map((m,i)=><button key={m} onPointerMove={e=>{if(e.buttons)setOpen(v=>v.map((x,j)=>j===i?true:x))}} onClick={()=>setOpen(v=>v.map((x,j)=>j===i?true:x))} className={`grid min-h-36 place-items-center rounded-lg border p-4 transition ${open[i]?"border-primary bg-rose-soft/40":"border-gold bg-secondary text-secondary-foreground"}`}>{open[i]?m:"✨ Scratch me ✨"}</button>)}</div></div>}
function LoveMeter({celebrate}:{celebrate:()=>void}){const [v,setV]=useState(0);const run=()=>{setV(0);let n=0;const id=setInterval(()=>{n+=2;setV(n);if(n>=100){clearInterval(id);celebrate()}},24)};return <div><h3 className="script text-4xl text-primary">How much do I love My Januu? 💘</h3><div className="mx-auto my-10 max-w-md"><div className="h-7 overflow-hidden rounded-full border border-border bg-muted"><div className="h-full bg-primary transition-all" style={{width:`${v}%`}}/></div><strong className="mt-3 block text-3xl text-primary">{v}%</strong></div>{v===100?<p className="text-xl font-semibold text-primary">Perfect Match! ❤️ 100% Forever</p>:<MagicButton onClick={run}>Check Our Love %</MagicButton>}</div>}
function Balloons({celebrate}:{celebrate:()=>void}){const msgs=["You're amazing! 🌟","You make me smile 😊","You're my favourite 💖","You're beautiful 🌸","You're my everything 💗"];const [popped,setPopped]=useState<number[]>([]);return <div><h3 className="script text-4xl text-primary">Balloon Pop 🎈</h3><div className="mt-8 flex min-h-48 flex-wrap items-center justify-center gap-4">{msgs.map((m,i)=><button key={m} onClick={()=>{const n=[...popped,i];setPopped(n);if(n.length===5)celebrate()}} className={`floaty grid h-32 w-24 place-items-center rounded-[50%_50%_45%_45%] border border-border p-2 text-xs transition ${popped.includes(i)?"bg-paper":"bg-rose-soft text-primary"}`}>{popped.includes(i)?m:"🎈"}</button>)}</div>{popped.length===5&&<p className="font-semibold text-primary">You win! Prize: one virtual hug 🤗</p>}</div>}
function EmojiGuess({celebrate}:{celebrate:()=>void}){const data=[["🌙 ⭐ 💕","love story"],["🌸 💗 ✨","lily and rose"],["🎂 🎉 🎈","birthday party"]];const [q,setQ]=useState(0);const [value,setValue]=useState("");const [msg,setMsg]=useState("");const check=()=>{if(value.trim().toLowerCase()===data[q][1]){setMsg("You got it! ✨");celebrate();setTimeout(()=>{setQ((q+1)%3);setValue("");setMsg("")},800)}else setMsg("Almost—try another little guess 💡")};return <div><h3 className="script text-4xl text-primary">Emoji Guess</h3><div className="my-8 text-5xl tracking-[.25em]">{data[q][0]}</div><div className="mx-auto flex max-w-md gap-2"><input value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>e.key==="Enter"&&check()} className="min-w-0 flex-1 rounded-full border border-border bg-background/60 px-4" placeholder="What does it mean?"/><MagicButton onClick={check}>Guess</MagicButton></div><p className="mt-4 text-sm text-primary">{msg}</p></div>}

function Letter({onNext}:{onNext:()=>void}){const [open,setOpen]=useState(false);return <div className="chapter flex min-h-[calc(100dvh-6rem)] items-center"><div className="mx-auto w-full max-w-3xl text-center"><h2 className="script text-5xl font-bold text-primary">A Letter From My Heart</h2>{!open?<button onClick={()=>setOpen(true)} className="floaty relative mx-auto mt-14 block h-52 w-72 rounded-lg bg-primary/75 shadow-2xl"><span className="absolute inset-x-0 top-0 h-0 border-x-[144px] border-t-[105px] border-x-transparent border-t-paper/50"/><span className="absolute inset-0 grid place-items-center text-5xl">💌</span><span className="absolute -bottom-10 inset-x-0 text-sm text-primary">Tap to open</span></button>:<div className="animate-fade-in relative mt-7 overflow-hidden rounded-sm bg-paper p-7 text-left shadow-2xl sm:p-12"><img src={floralWreath} alt="" loading="lazy" width={1024} height={1024} className="pointer-events-none absolute inset-0 size-full object-cover opacity-15"/><div className="relative"><p className="script text-3xl font-bold text-primary">My Dearest Januu,</p><p className="quote mt-5 whitespace-pre-line text-lg leading-8 italic">You are my world. Every day with you is special. This surprise was made for you, because you deserve all the happiness in the world.{"\n\n"}Thank you for being you. Happy Birthday, my love! ❤️</p><p className="script mt-7 text-right text-2xl text-primary">— Yours forever, Uzan Khan</p></div><div className="mt-7 text-center"><MagicButton onClick={onNext}>One last surprise <ArrowRight size={18}/></MagicButton></div></div>}</div></div>}

function Finale({celebrate,onReplay}:{celebrate:()=>void;onReplay:()=>void}){const [revealed,setRevealed]=useState(false);useEffect(()=>{celebrate()},[]);return <div className="chapter flex min-h-[calc(100dvh-6rem)] items-center"><div className="mx-auto max-w-4xl text-center"><p className="text-6xl">🎁</p><h2 className="script mt-4 text-6xl font-bold text-primary sm:text-8xl">Happy Birthday, My Januu!</h2><p className="quote mt-6 text-xl italic">You are loved. Always.</p><p className="script mt-2 text-3xl text-primary">— Uzan Khan 💗</p><button onClick={()=>setRevealed(true)} className="group mx-auto mt-9 block rounded-lg border border-border bg-paper/65 px-7 py-5 text-sm text-muted-foreground transition hover:bg-paper focus:bg-paper"><span className="group-hover:hidden group-focus:hidden">A tiny secret is hiding here…</span><strong className={`${revealed?"block":"hidden group-hover:block group-focus:block"} text-primary`}>In every lifetime, I would still choose you. ✨</strong></button><div className="mt-10 flex flex-wrap justify-center gap-3"><MagicButton onClick={celebrate}>More magic ✨</MagicButton><button onClick={onReplay} className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-paper px-6 py-3 font-semibold text-primary"><RotateCcw size={17}/> Replay our story</button></div><Music2 className="mx-auto mt-10 text-gold"/></div></div>}
